# Pytorch

In [1]:
import pygame
import random

Starting_blue_blobs = 10
Starting_red_blobs = 3

WIDTH = 800
HEIGHT = 600
WHITE = (255,255,255)
BLUE = (0,0,255)
RED = (255,0,0)

game_display = pygame.display.set_mode((WIDTH , HEIGHT))
pygame.display.set_caption("FIRST GAME")
clock = pygame.time.Clock()


class Blob:
    def __init__(self, color):
        self.x = random.randrange(0 , WIDTH)
        self.y = random.randrange(0 , HEIGHT)
        self.size = random.randrange(4,8)
        self.color = color
    def move(self):
        self.move_x = random.randrange(-1,2)
        self.move_y = random.randrange(-1,2)
        self.x += self.move_x
        self.y += self.move_y
        
        if self.x < 0 : self.x = 0
        elif self.x > WIDTH : self.x = WIDTH
        
        if self.y < 0 : self.y = 0
        elif self.y > HEIGHT :  self.y = HEIGHT


def draw_environment(blob_list):
    game_display.fill(WHITE)
    
    for blob_dict in blob_list:
        for blob_id in blob_dict:
            blob = blob_dict[blob_id]
            pygame.draw.circle(game_display , blob.color , [blob.x , blob.y] , blob.size)
            blob.move()
    pygame.display.update()
    
    
def main():
    blue_blobs = dict(enumerate([Blob(BLUE) for i in range(Starting_blue_blobs)]))
    red_blobs = dict(enumerate([Blob(RED) for i in range(Starting_red_blobs)]))
    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT :
                pygame.quit()
                quit()
        draw_environment([blue_blobs,red_blobs])
        clock.tick(60)
        
        
if __name__ == '__main__':
    main()
        

pygame 2.0.1 (SDL 2.0.14, Python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html


error: display Surface quit

In [2]:
import torch

x = torch.tensor([3,5])
y = torch.tensor([2,2])

print(x*y)

tensor([ 6, 10])


In [3]:
x = torch.zeros([3,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
y = torch.rand([2,3])
y

tensor([[0.1654, 0.8922, 0.3168],
        [0.1930, 0.3742, 0.9919]])

In [5]:
y.view([1,6])

tensor([[0.1654, 0.8922, 0.3168, 0.1930, 0.3742, 0.9919]])

In [ ]:
import torch
import torchvision
from torchvision import transforms , datasets
